//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleTest10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIN
    {
        public decimal ID { get; set; }
        public string RECPT_STREET { get; set; }
        public string RECPT_ZIP_CODE { get; set; }
        public string RECPT_CITY { get; set; }
        public string POD { get; set; }
        public string INVOICE_TYPE { get; set; }
        public Nullable<System.DateTime> ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string CNTR_ACCT { get; set; }
        public string PARTNER { get; set; }
        public string MUNIC { get; set; }
        public string OFFICE { get; set; }
        public string DIADROMI { get; set; }
        public string BK { get; set; }
        public string SELIDA { get; set; }
        public string ZIP_CODE_B { get; set; }
        public Nullable<decimal> CNT_INVC_ZC { get; set; }
        public Nullable<decimal> JULIAN_DATE { get; set; }
        public Nullable<decimal> LINE_NBR_AMF { get; set; }
        public string FILLER1 { get; set; }
        public string POD2 { get; set; }
        public string DISCON_DATE { get; set; }
        public string CHK_DIG1 { get; set; }
        public Nullable<decimal> AMNT { get; set; }
        public string CHK_DIG2 { get; set; }
        public Nullable<System.DateTime> GREG_DATE { get; set; }
        public string UNDELIV_TYPE { get; set; }
        public string UNDELIV_CAUSE { get; set; }
        public Nullable<decimal> PACK_NBR { get; set; }
        public string PACK_NAME { get; set; }
        public string DELIV_STREET { get; set; }
        public string DELIV_ZIP_CODE { get; set; }
        public string DELIV_CITY { get; set; }
    
        public virtual INVOICE_TYPE INVOICE_TYPE1 { get; set; }
        public virtual ZIP_CODE ZIP_CODE { get; set; }
        public virtual MUNIC MUNIC1 { get; set; }
        public virtual OFFICE OFFICE1 { get; set; }
        public virtual ZIP_CODE ZIP_CODE1 { get; set; }
        public virtual UNDEL_CAUSE UNDEL_CAUSE { get; set; }
        public virtual UNDEL_TYPE UNDEL_TYPE { get; set; }
    }
}
