//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleTest10.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OREntities : DbContext
    {
        public OREntities()
            : base("name=OREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BSNS_AREA> BSNS_AREA { get; set; }
        public DbSet<OFFICE> OFFICEs { get; set; }
        public DbSet<USER_TYPE> USER_TYPE { get; set; }
        public DbSet<USR> USRs { get; set; }
        public DbSet<INVOICE_TYPE> INVOICE_TYPE { get; set; }
        public DbSet<MUNIC> MUNICs { get; set; }
        public DbSet<UNDEL_CAUSE> UNDEL_CAUSE { get; set; }
        public DbSet<UNDEL_TYPE> UNDEL_TYPE { get; set; }
        public DbSet<ZIP_CODE> ZIP_CODE { get; set; }
        public DbSet<MAIN> MAINs { get; set; }
    }
}
