//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleTest10.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class USR
    {
        // [DisplayName] = Define Display Name for attribute
        // [Required()] = Define field is required with error message
        [DisplayName("ID:")]
        [Required(ErrorMessage = "This field is required")]
        public string ID { get; set; }



        // [DisplayName] = Define Display Name for Attribute
        // [DataType()] = Define data annotation (*) for password
        // [Required()] = Define field is required with error message
        [DisplayName("Pass Word:")]
        //[DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required")]
        public string PASSWORD { get; set; }

        // [DisplayName] = Define Display Name for attribute
        // [Required()] = Define field is required with error message
        public string AM { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string FATHER_NAME { get; set; }
        public string UNIT { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string TYPE { get; set; }
    
        public virtual USER_TYPE USER_TYPE { get; set; }

        // This was added post DB first class creation
        // to handle login error messages.
        public string LoginErrorMessage { get; set; }
    }
}
