//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleTest10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZIP_CODE
    {
        public ZIP_CODE()
        {
            this.MAINs = new HashSet<MAIN>();
            this.MAINs1 = new HashSet<MAIN>();
        }
    
        public string ID { get; set; }
    
        public virtual ICollection<MAIN> MAINs { get; set; }
        public virtual ICollection<MAIN> MAINs1 { get; set; }
    }
}
